version: '3.2'

services:
  tor-browser:
    image: dperson/torproxy
    container_name: tor-browser
    ports:
      - '8118:8118'
      - '9051:9051'
    networks:
      - webappnetwork
  web:
    container_name: threatenMeBackend
    build: .
    ports:
      - '8081:8081'
    depends_on:
      - tor-browser
    networks:F
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
